import test from "node:test";
import assert from "node:assert/strict";
import {webcrypto} from "node:crypto";
import {readFile} from "node:fs/promises";
import {summary,setConfirmed,stateKey,parseState,decryptSnapshot} from "../3.1-kith-inn/order-ledger/shared/model.mjs";
const order={id:"demo-001",amount:30,payment:"none"};
function storage(){const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)}}
test("手动确认、重新读取与撤销保留原付款来源",()=>{const s=storage();setConfirmed(s,"taozi",order,true);const saved=parseState(s.getItem(stateKey("taozi")));assert.equal(summary([order],saved).pending,0);setConfirmed(s,"taozi",order,false);assert.equal(summary([order],parseState(s.getItem(stateKey("taozi")))).pending,1);assert.equal(order.payment,"none")});
test("群之间、订单之间互不串用确认状态",()=>{const s=storage();setConfirmed(s,"taozi",order,true);assert.equal(summary([order],parseState(s.getItem(stateKey("yuma")))).done,0);assert.equal(summary([{...order,id:"demo-002"}],parseState(s.getItem(stateKey("taozi")))).done,0)});
test("存储失败抛错，不返回伪造成功记录",()=>{const s={getItem:()=>null,setItem:()=>{throw Error("quota")}};assert.throws(()=>setConfirmed(s,"taozi",order,true),/quota/)});
test("损坏记录不静默覆盖",()=>{assert.throws(()=>parseState("oops"));assert.throws(()=>parseState('[1]'));assert.throws(()=>parseState('{"id":{"confirmed":"yes"}}'))});
test("已有群内回执不能被手动撤销",()=>{assert.throws(()=>setConfirmed(storage(),"x",{...order,payment:"paid"},false))});
test("待收转账、未知红包和未知单价不会自动计入已核对金额",()=>{const rows=[{id:"a",amount:19,payment:"paid"},{id:"b",amount:16,payment:"sent"},{id:"c",amount:24,payment:"redpacket"},{id:"d",amount:null,payment:"none"}];assert.deepEqual(summary(rows,{}),{count:4,done:1,pending:3,total:59,confirmed:19,unknown:1})});
test("解锁密钥和群标识必须同时匹配，篡改快照会失败",async()=>{const raw=webcrypto.getRandomValues(new Uint8Array(32)),iv=webcrypto.getRandomValues(new Uint8Array(12));const key=await webcrypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt"]);const data={group:"测试群",orders:[],dates:[]};const ct=await webcrypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:new TextEncoder().encode("taozi")},key,new TextEncoder().encode(JSON.stringify(data)));const envelope={version:1,algorithm:"AES-GCM",iv:Buffer.from(iv).toString("base64"),data:Buffer.from(ct).toString("base64")};const encoded=Buffer.from(raw).toString("base64url");assert.deepEqual(await decryptSnapshot(envelope,encoded,"taozi"),data);await assert.rejects(decryptSnapshot(envelope,encoded,"yuma"));await assert.rejects(decryptSnapshot(envelope,Buffer.alloc(32).toString("base64url"),"taozi"));const changed=Buffer.from(ct);changed[0]^=1;await assert.rejects(decryptSnapshot({...envelope,data:changed.toString("base64")},encoded,"taozi"))});
test("三个入口共用代码且不含明文订单",async()=>{for(const group of ["taozi","jingjing","yuma"]){const html=await readFile(new URL(`../3.1-kith-inn/order-ledger/${group}/index.html`,import.meta.url),"utf8");assert.match(html,/\.\.\/shared\/app.mjs/);assert.match(html,/no-referrer/);const payload=JSON.parse(await readFile(new URL(`../3.1-kith-inn/order-ledger/${group}/snapshot.json`,import.meta.url),"utf8"));assert.equal(payload.algorithm,"AES-GCM");assert.equal(payload.orders,undefined);assert.equal(payload.key,undefined)}});
