"use client";
import { useEffect,useRef,useState } from "react";
import { Check,CheckCheck,ClipboardList,Clock3,RefreshCw,ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Table,TableHeader,TableHead,TableRow,TableBody,TableCell } from "@/components/ui/table";
import type { LedgerData,Order } from "./types";
import { restoreGroupSession } from "@/lib/browser-session";
import { ShareButton } from "@/components/share-button";
import { selectedDate } from "@/lib/selected-date";
const money=(n:number)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2}).format(n);
const paid=(o:Order)=>o.payment==="paid"||o.manual;
const snapshotTime=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?"时间待核":new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(date)+"（北京时间）";};
const beijingDate=(now=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(now);
const orderedDates=(dates:string[],today:string)=>[today,...dates.filter(d=>d!==today).sort((a,b)=>b.localeCompare(a))];
export default function Ledger({group}:{group:string}){
 const endpoint=`/api/ledger?group=${encodeURIComponent(group)}`;
 const [data,setData]=useState<LedgerData|null>(null),[date,setDate]=useState(""),[error,setError]=useState(""),[login,setLogin]=useState(false),[busy,setBusy]=useState<string[]>([]),[refreshing,setRefreshing]=useState(false),[notice,setNotice]=useState("");
 const loading=useRef(false),enteredWithKey=useRef<boolean|null>(null),linkedDate=useRef<string|null>(null);
 async function load(){if(loading.current)return;loading.current=true;setRefreshing(true);try{if(enteredWithKey.current===null){enteredWithKey.current=new URLSearchParams(window.location.hash.slice(1)).has("key");linkedDate.current=new URLSearchParams(window.location.search).get("date");}if(!await restoreGroupSession(group)){setError("专属链接已失效或与该群不符，请使用对应群的完整链接。");setLogin(true);return}const r=await fetch(endpoint,{cache:"no-store"});if(r.status===401){setLogin(true);return}if(r.status===403)throw Error("此链接没有访问该群的权限。");if(!r.ok)throw Error("暂时无法读取记录，请重试。");const d:LedgerData=await r.json();setData(d);setDate(current=>selectedDate(current||((linkedDate.current===beijingDate()||d.dates.includes(linkedDate.current??""))?linkedDate.current??"":""),beijingDate(),d.dates,d.orders,enteredWithKey.current===true));setLogin(false);setError("");}catch(e){setError((e as Error).message)}finally{loading.current=false;setRefreshing(false)}}
 useEffect(()=>{void load()},[group]);
 async function confirm(o:Order,value:boolean){setBusy(b=>[...b,o.id]);setNotice("");try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id,confirmed:value,version:o.version})});const result=await r.json() as {error?:string;orderId:string;manual:boolean;version:number;confirmedAt:string};if(!r.ok){if(r.status===409)await load();throw Error(result.error||"保存失败，请重试")};setData(d=>d?{...d,orders:d.orders.map(row=>row.id===o.id?{...row,...result}:row)}:d);setNotice(value?`已确认 ${o.customer} 的付款`:`已撤销 ${o.customer} 的手动确认`);setError("");}catch(e){setError((e as Error).message)}finally{setBusy(b=>b.filter(x=>x!==o.id))}}
 if(login)return <div className="login"><div className="mark"><ShieldCheck size={20}/></div><h1>请使用群主的完整专属链接</h1><p className="subtitle">订单和收款记录仅向持有此群专属链接的人展示。</p>{error&&<p className="error">{error}</p>}</div>;
 if(!data)return <main className="shell"><div className="topline"><span className="mark"><ClipboardList size={20}/></span>每日对账</div>{error?<div className="error">{error}<Button onClick={load}>重试</Button></div>:<div className="loading">正在读取订单与收款记录…</div>}</main>;
 const today=beijingDate(),dates=orderedDates(data.dates,today);
 const orders=data.orders.filter(o=>o.date===date),done=orders.filter(paid),pending=orders.length-done.length,total=orders.reduce((s,o)=>s+(o.amount??0),0),confirmed=done.reduce((s,o)=>s+(o.amount??0),0),unknown=orders.filter(o=>o.amount===null).length;
 const notes=data.exceptions.filter(e=>e.date===date);
 function status(o:Order){const kind=o.manual?"manual":o.payment;const label={paid:"群内已收款",manual:"群主已确认",sent:"已转账 · 待收款",redpacket:"红包 · 待核金额",none:"未见群内付款"}[kind];return <div><span className={`status ${kind}`}>{paid(o)?<Check size={14}/>:o.payment!=="none"?<Clock3 size={14}/>:null}{label}</span>{o.manual?<div className="status-note">原记录：{o.payment==="sent"?"已转账待收款":o.payment==="redpacket"?"红包金额未知":"未见群内付款"}</div>:null}</div>}
 function action(o:Order){return o.payment==="paid"?<span className="status-note">已有收款回执</span>:o.manual?<button className="undo" disabled={busy.includes(o.id)} aria-label={`撤销${o.customer}的手动确认`} onClick={()=>confirm(o,false)}>{busy.includes(o.id)?"保存中…":"撤销确认"}</button>:<Button variant="outline" className="confirm" disabled={busy.includes(o.id)} aria-label={`手动确认${o.customer}已付款`} onClick={()=>confirm(o,true)}>{busy.includes(o.id)?"保存中…":<><Check size={15}/>手动确认已付</>}</Button>}
 return <main className="shell"><div className="topline"><span className="mark"><ClipboardList size={20}/></span><span>每日对账</span><div className="top-actions"><span className="owner-label"><ShieldCheck size={15}/>群主工作台</span><ShareButton group={group} date={date} data={data} disabled={refreshing||busy.length>0}/></div></div><h1>{data.group}</h1>
 <Tabs value={date} onValueChange={setDate}><div className="datebar"><TabsList className="date-tabs" style={{maxWidth:"100%",overflowX:"auto",justifyContent:"flex-start"}} aria-label="选择订单日期">{dates.map(d=><TabsTrigger className="date-tab" key={d} value={d}>{d===today?"今天 · ":""}{Number(d.slice(5,7))}月{Number(d.slice(8))}日<span style={{fontSize:12,opacity:.65,marginLeft:6}}>{["日","一","二","三","四","五","六"][new Date(d+"T12:00:00+08:00").getUTCDay()]}</span></TabsTrigger>)}</TabsList><div><span className="live">{data.syncedAt?"最近同步":"数据更新"} {snapshotTime(data.syncedAt??data.snapshot)}</span><button className="plain-button" onClick={load} disabled={refreshing||busy.length>0} aria-label="刷新对账状态"><RefreshCw size={14} style={{display:"inline",marginLeft:10}}/> {refreshing?"读取中":"刷新"}</button></div></div>
 {dates.map(d=><TabsContent key={d} value={d}>{d===date&&<><div className="stats"><div className="stat"><span className="label">当天订单</span><strong>{orders.length}<span className="unit">笔</span></strong></div><div className="stat"><span className="label">已知应收金额</span><strong><span className="unit" style={{margin:0}}>¥ </span>{money(total)}</strong>{unknown>0&&<div className="subtitle">另{unknown}笔金额待核实</div>}</div><div className="stat done"><span className="label">已核对订单金额</span><strong><span className="unit" style={{margin:0}}>¥ </span>{money(confirmed)}</strong><div className="subtitle">群内已收或群主确认</div></div><div className={`stat ${pending?"pending":"done"}`}><span className="label">待核对订单</span><strong>{pending}<span className="unit">笔</span></strong></div></div>
 {orders.length>0&&<div className={`reconcile ${pending===0?"complete":""}`}>{pending===0?<CheckCheck size={25}/>:<ClipboardList size={25}/>}<div style={{flex:1}}><strong>{pending===0?"当天订单对账完成":`已核对 ${done.length} / ${orders.length} 笔订单`}</strong><p>{pending===0?"所有订单均已确认付款。手动确认记录已保存。":"核实私聊转账、红包或现金收款后，点击「手动确认已付」。"}</p><div className="progress-track"><span style={{width:`${done.length/orders.length*100}%`}}/></div></div></div>}
 {error&&<div className="error" role="alert">{error}</div>}<div className="sr-only" role="status" aria-live="polite">{notice}</div>
 <div className="section-head"><h2>下单客户</h2><span className="subtitle">{date.replaceAll("-",".")}</span></div>
 {orders.length===0?<div className="panel empty">该日期暂无已同步的订单记录。</div>:<div className="panel"><div className="desktop-orders"><Table className="order-table"><TableHeader><TableRow><TableHead>客户昵称</TableHead><TableHead>商品 · 分量</TableHead><TableHead>应收</TableHead><TableHead>群内付款 / 对账状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{orders.map(o=><TableRow key={o.id}><TableCell><div className="name">{o.customer}</div><div className="location">{o.location||"未注明房号"}</div></TableCell><TableCell><div className="item">{o.item} · {o.quantity}<small>{o.note}</small></div></TableCell><TableCell className="amount">{o.amount===null?"待核实":`¥${money(o.amount)}`}</TableCell><TableCell>{status(o)}</TableCell><TableCell>{action(o)}</TableCell></TableRow>)}</TableBody></Table></div><div className="mobile-orders">{orders.map(o=><article className="order-card" key={o.id}><div className="card-top"><div><div className="name">{o.customer}</div><div className="location">{o.location||"未注明房号"}</div></div><div className="amount">{o.amount===null?"金额待核":`¥${money(o.amount)}`}</div></div><div className="card-items item">{o.item} · {o.quantity}<small>{o.note}</small></div><div className="card-bottom">{status(o)}{action(o)}</div></article>)}</div></div>}
 <p className="footnote">手动确认保存在云端，其他设备刷新后可读取。「未见群内付款」不代表欠款。手动确认只更新对账记录，不会发起转账，也不会修改微信消息。</p>{notes.length>0&&<section className="exceptions"><h2>另有这些记录需要留意</h2>{notes.map((n,i)=><div className="exception" key={i}>{n.text}</div>)}</section>}
 </>}</TabsContent>)}</Tabs></main>
}
